### ISSUE TITLE
Adding docker implementation of this 

### ISSUE THREAD

**Issue by vishwajeetdabholkar** [vishwajeetdabholkar/resume_parser_api#1]
Creating a working docker version of this.
The docker should run on linux distro with all the dependencies like tesseract and propellor handled.

**Comment by gnanesh-16** [comment]
Hey, @vishwajeetdabholkar I noticed that the integration of Docker for the app  is currently not being assigned. I would love to contribute to this project and have drafted my pull request for your review.

**Comment by vishwajeetdabholkar** [comment]
@gnanesh-16 assigned to you
